language: objective-c
# xcode_project: SwiftyJSONAPI.xcodeproj
# xcode_scheme: SwiftyJSONAPI
osx_image: xcode9.3beta
script:
    - xcodebuild clean build test -project SwiftyJSONAPI.xcodeproj -scheme SwiftyJSONAPI -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3'

